// ── AFCN LeanPath surplus data ──────────────────────────────────────────
// Source: /mnt/user-data/uploads/Waste-Data.csv
// Generated: 2026-03-10 23:10
// Entries: 30 rescuable groups · 1051 lbs total
// Urgency: 6 Critical · 12 Soon · 12 Stable
// Regenerate: python scripts/parse_leanpath.py data/Waste-Data.csv
// ─────────────────────────────────────────────────────────────────────────

const MOCK_SURPLUS = [
  { id: 1, name: "North Ave Dining Hall",
    lng: -84.3918, lat: 33.7716,
    food_type: "Packaged Goods", quantity_lbs: 63.8,
    expiration: "2026-03-10T23:55:11", urgency: "Critical",
    transport: "Dry Vehicle", source_category: "GT Campus",
    notes: "Overproduction · Beans, Potatoes, Rice · International, Mindful Bites, Vegan / ",
    cost_usd: 39.68, leanpath_category: "Starch" },
  { id: 2, name: "West Village Dining Commons",
    lng: -84.4057, lat: 33.776,
    food_type: "Produce", quantity_lbs: 61.9,
    expiration: "2026-03-10T23:55:11", urgency: "Critical",
    transport: "Dry Vehicle", source_category: "GT Campus",
    notes: "Overproduction · Vegetables · Tech Taqueria, White & Gold Grill",
    cost_usd: 47.07, leanpath_category: "Fruit-Vegetable" },
  { id: 3, name: "North Ave Dining Hall",
    lng: -84.3918, lat: 33.7716,
    food_type: "Produce", quantity_lbs: 61.7,
    expiration: "2026-03-10T23:55:11", urgency: "Critical",
    transport: "Dry Vehicle", source_category: "GT Campus",
    notes: "Overproduction · Fruit, Vegetables · BOH Kitchen, International, Salad Bar",
    cost_usd: 90.71, leanpath_category: "Fruit-Vegetable" },
  { id: 4, name: "North Ave Dining Hall",
    lng: -84.3918, lat: 33.7716,
    food_type: "Produce", quantity_lbs: 55.4,
    expiration: "2026-03-10T23:55:11", urgency: "Critical",
    transport: "Dry Vehicle", source_category: "GT Campus",
    notes: "Overproduction · Fruit, Vegetables · BOH Kitchen, Grill, Other Source, Sala",
    cost_usd: 42.86, leanpath_category: "Fruit-Vegetable" },
  { id: 5, name: "North Ave Dining Hall",
    lng: -84.3918, lat: 33.7716,
    food_type: "Prepared Meals", quantity_lbs: 51.8,
    expiration: "2026-03-10T23:55:11", urgency: "Critical",
    transport: "Refrigerated Van", source_category: "GT Campus",
    notes: "Overproduction · Casserole, Mixed Plate-Other, Pizza w Toppings · BOH Kitchen, Internation",
    cost_usd: 68.83, leanpath_category: "Mixed Foods" },
  { id: 6, name: "West Village Dining Commons",
    lng: -84.4057, lat: 33.776,
    food_type: "Packaged Goods", quantity_lbs: 51.8,
    expiration: "2026-03-10T23:55:11", urgency: "Critical",
    transport: "Dry Vehicle", source_category: "GT Campus",
    notes: "Overproduction · Beans, Rice · BOH Kitchen, Tech Taqueria, White & Go",
    cost_usd: 28.86, leanpath_category: "Starch" },
  { id: 7, name: "West Village Dining Commons",
    lng: -84.4057, lat: 33.776,
    food_type: "Produce", quantity_lbs: 50.6,
    expiration: "2026-03-11T02:40:11", urgency: "Soon",
    transport: "Dry Vehicle", source_category: "GT Campus",
    notes: "Overproduction · Vegetables · Leaning Tower Pizza, White & Gold Gril",
    cost_usd: 38.46, leanpath_category: "Fruit-Vegetable" },
  { id: 8, name: "West Village Dining Commons",
    lng: -84.4057, lat: 33.776,
    food_type: "Produce", quantity_lbs: 49.5,
    expiration: "2026-03-11T02:40:11", urgency: "Soon",
    transport: "Dry Vehicle", source_category: "GT Campus",
    notes: "Overproduction · Fruit, Vegetables · Tech Taqueria, White & Gold Grill",
    cost_usd: 78.93, leanpath_category: "Fruit-Vegetable" },
  { id: 9, name: "North Ave Dining Hall",
    lng: -84.3918, lat: 33.7716,
    food_type: "Produce", quantity_lbs: 46.0,
    expiration: "2026-03-11T02:40:11", urgency: "Soon",
    transport: "Dry Vehicle", source_category: "GT Campus",
    notes: "Overproduction · Fruit, Vegetables · Grill, International, Other Source, Sa",
    cost_usd: 54.22, leanpath_category: "Fruit-Vegetable" },
  { id: 10, name: "North Ave Dining Hall",
    lng: -84.3918, lat: 33.7716,
    food_type: "Packaged Goods", quantity_lbs: 41.3,
    expiration: "2026-03-11T02:40:11", urgency: "Soon",
    transport: "Dry Vehicle", source_category: "GT Campus",
    notes: "Overproduction · Beans, Potatoes, Rice · BOH Kitchen, International, Other Sour",
    cost_usd: 25.8, leanpath_category: "Starch" },
  { id: 11, name: "North Ave Dining Hall",
    lng: -84.3918, lat: 33.7716,
    food_type: "Produce", quantity_lbs: 39.1,
    expiration: "2026-03-11T02:40:11", urgency: "Soon",
    transport: "Dry Vehicle", source_category: "GT Campus",
    notes: "Overproduction · Vegetables · BOH Kitchen, Mindful Bites",
    cost_usd: 29.7, leanpath_category: "Fruit-Vegetable" },
  { id: 12, name: "North Ave Dining Hall",
    lng: -84.3918, lat: 33.7716,
    food_type: "Prepared Meals", quantity_lbs: 32.9,
    expiration: "2026-03-11T02:40:11", urgency: "Soon",
    transport: "Refrigerated Van", source_category: "GT Campus",
    notes: "Overproduction · Beef - Ground, Chicken - Boneless, Deli Meat · BOH Kitchen, Grill, Mindfu",
    cost_usd: 99.54, leanpath_category: "Meat-Protein" },
  { id: 13, name: "North Ave Dining Hall",
    lng: -84.3918, lat: 33.7716,
    food_type: "Prepared Meals", quantity_lbs: 32.2,
    expiration: "2026-03-11T02:40:11", urgency: "Soon",
    transport: "Refrigerated Van", source_category: "GT Campus",
    notes: "Overproduction · Deli Meat, Pork, Tofu · BOH Kitchen, International, Other Sour",
    cost_usd: 97.72, leanpath_category: "Meat-Protein" },
  { id: 14, name: "West Village Dining Commons",
    lng: -84.4057, lat: 33.776,
    food_type: "Packaged Goods", quantity_lbs: 31.7,
    expiration: "2026-03-11T02:40:11", urgency: "Soon",
    transport: "Dry Vehicle", source_category: "GT Campus",
    notes: "Overproduction · Beans, Fries, Pasta · Mindful Bites, White & Gold Grill",
    cost_usd: 25.36, leanpath_category: "Starch" },
  { id: 15, name: "West Village Dining Commons",
    lng: -84.4057, lat: 33.776,
    food_type: "Prepared Meals", quantity_lbs: 30.2,
    expiration: "2026-03-11T02:40:11", urgency: "Soon",
    transport: "Refrigerated Van", source_category: "GT Campus",
    notes: "Overproduction · Beef - Whole, Chicken-Bone-in, Pork · Leaning Tower Pizza, White & Gold G",
    cost_usd: 123.74, leanpath_category: "Meat-Protein" },
  { id: 16, name: "North Ave Dining Hall",
    lng: -84.3918, lat: 33.7716,
    food_type: "Perishable", quantity_lbs: 28.9,
    expiration: "2026-03-11T02:40:11", urgency: "Soon",
    transport: "Refrigerated Van", source_category: "GT Campus",
    notes: "Overproduction · Eggs · International, Other Source",
    cost_usd: 30.64, leanpath_category: "Dairy & Eggs" },
  { id: 17, name: "North Ave Dining Hall",
    lng: -84.3918, lat: 33.7716,
    food_type: "Bakery", quantity_lbs: 28.0,
    expiration: "2026-03-11T02:40:11", urgency: "Soon",
    transport: "Dry Vehicle", source_category: "GT Campus",
    notes: "Overproduction · Bread, Hot Cereal · BOH Kitchen, International, Other Sour",
    cost_usd: 16.06, leanpath_category: "Bread-Cereal" },
  { id: 18, name: "North Ave Dining Hall",
    lng: -84.3918, lat: 33.7716,
    food_type: "Packaged Goods", quantity_lbs: 26.4,
    expiration: "2026-03-11T02:40:11", urgency: "Soon",
    transport: "Dry Vehicle", source_category: "GT Campus",
    notes: "Overproduction · Pasta, Rice · BOH Kitchen",
    cost_usd: 18.67, leanpath_category: "Starch" },
  { id: 19, name: "North Ave Dining Hall",
    lng: -84.3918, lat: 33.7716,
    food_type: "Bakery", quantity_lbs: 26.0,
    expiration: "2026-03-11T07:10:11", urgency: "Stable",
    transport: "Dry Vehicle", source_category: "GT Campus",
    notes: "Overproduction · Hot Cereal · International",
    cost_usd: 11.69, leanpath_category: "Bread-Cereal" },
  { id: 20, name: "North Ave Dining Hall",
    lng: -84.3918, lat: 33.7716,
    food_type: "Bakery", quantity_lbs: 25.5,
    expiration: "2026-03-11T07:10:11", urgency: "Stable",
    transport: "Dry Vehicle", source_category: "GT Campus",
    notes: "Overproduction · Hot Cereal · International, Other Source",
    cost_usd: 11.49, leanpath_category: "Bread-Cereal" },
  { id: 21, name: "North Ave Dining Hall",
    lng: -84.3918, lat: 33.7716,
    food_type: "Prepared Meals", quantity_lbs: 25.2,
    expiration: "2026-03-11T07:10:11", urgency: "Stable",
    transport: "Refrigerated Van", source_category: "GT Campus",
    notes: "Overproduction · Fish, Pork · BOH Kitchen, International",
    cost_usd: 87.35, leanpath_category: "Meat-Protein" },
  { id: 22, name: "North Ave Dining Hall",
    lng: -84.3918, lat: 33.7716,
    food_type: "Prepared Meals", quantity_lbs: 22.6,
    expiration: "2026-03-11T07:10:11", urgency: "Stable",
    transport: "Refrigerated Van", source_category: "GT Campus",
    notes: "Overproduction · Casserole, Pizza w Toppings · BOH Kitchen, Other Source, Pizza Stati",
    cost_usd: 47.33, leanpath_category: "Mixed Foods" },
  { id: 23, name: "North Ave Dining Hall",
    lng: -84.3918, lat: 33.7716,
    food_type: "Prepared Meals", quantity_lbs: 22.6,
    expiration: "2026-03-11T07:10:11", urgency: "Stable",
    transport: "Refrigerated Van", source_category: "GT Campus",
    notes: "Overproduction · Chicken - Boneless, Fish, Pork · BOH Kitchen, International, Other Sour",
    cost_usd: 59.99, leanpath_category: "Meat-Protein" },
  { id: 24, name: "North Ave Dining Hall",
    lng: -84.3918, lat: 33.7716,
    food_type: "Prepared Meals", quantity_lbs: 22.4,
    expiration: "2026-03-11T07:10:11", urgency: "Stable",
    transport: "Refrigerated Van", source_category: "GT Campus",
    notes: "Overproduction · Broth, Sauce · Other Source",
    cost_usd: 28.17, leanpath_category: "Soup-Sauce-Gravy" },
  { id: 25, name: "North Ave Dining Hall",
    lng: -84.3918, lat: 33.7716,
    food_type: "Produce", quantity_lbs: 22.3,
    expiration: "2026-03-11T07:10:11", urgency: "Stable",
    transport: "Dry Vehicle", source_category: "GT Campus",
    notes: "Overproduction · Vegetables · International, Mindful Bites, Other So",
    cost_usd: 16.97, leanpath_category: "Fruit-Vegetable" },
  { id: 26, name: "North Ave Dining Hall",
    lng: -84.3918, lat: 33.7716,
    food_type: "Produce", quantity_lbs: 21.3,
    expiration: "2026-03-11T07:10:11", urgency: "Stable",
    transport: "Dry Vehicle", source_category: "GT Campus",
    notes: "Overproduction · Fruit, Vegetables · International, Pizza Station, Salad Ba",
    cost_usd: 25.93, leanpath_category: "Fruit-Vegetable" },
  { id: 27, name: "West Village Dining Commons",
    lng: -84.4057, lat: 33.776,
    food_type: "Prepared Meals", quantity_lbs: 20.9,
    expiration: "2026-03-11T07:10:11", urgency: "Stable",
    transport: "Refrigerated Van", source_category: "GT Campus",
    notes: "Overproduction · Mixed Protein · Leaning Tower Pizza",
    cost_usd: 26.11, leanpath_category: "Mixed Foods" },
  { id: 28, name: "Student Center Food Court",
    lng: -84.3963, lat: 33.7748,
    food_type: "Prepared Meals", quantity_lbs: 20.3,
    expiration: "2026-03-11T07:10:11", urgency: "Stable",
    transport: "Refrigerated Van", source_category: "GT Campus",
    notes: "Quality Issue · Fish · Bento",
    cost_usd: 80.02, leanpath_category: "Meat-Protein" },
  { id: 29, name: "Exhibition Hall Express",
    lng: -84.394, lat: 33.7742,
    food_type: "Packaged Goods", quantity_lbs: 19.3,
    expiration: "2026-03-11T07:10:11", urgency: "Stable",
    transport: "Dry Vehicle", source_category: "GT Campus",
    notes: "Overproduction · Rice · BOH Post Event",
    cost_usd: 11.8, leanpath_category: "Starch" },
  { id: 30, name: "North Ave Dining Hall",
    lng: -84.3918, lat: 33.7716,
    food_type: "Bakery", quantity_lbs: 19.3,
    expiration: "2026-03-11T07:10:11", urgency: "Stable",
    transport: "Dry Vehicle", source_category: "GT Campus",
    notes: "Overproduction · Hot Cereal · International, Other Source",
    cost_usd: 8.7, leanpath_category: "Bread-Cereal" },
];

// ── Fleet stats (real LeanPath numbers) ──────────────────────────────────
const MOCK_FLEET = {
  activeDrivers:        38,
  refrigeratedVehicles: 8,
  avgPickupMin:         24,
  lbsTodayRecovered:    281.8,   // LeanPath: 2026-03-10
  lbsWeekRecovered:     2316.2,    // LeanPath: 2026-03-04 – 2026-03-10
  donationRatePct:      3.5,         // real: donated / total wasted
  costAtRisk:           2379.57,          // real: 7-day food cost
  topLocation:          "North Ave Dining Hall",
  topLocationLbs:       1632.1,
};
